### ISSUE TITLE
minimap遮挡问题

### ISSUE THREAD

**Issue by Using1174** [shalldie/vscode-background#111]
当图片设置为背景时，如果有开启小地图，会遮住图片。

![image](https://user-images.githubusercontent.com/16488261/40836873-f78a595a-65ca-11e8-97a0-c41c52f378ef.png)

是否考虑增加css使minimap在未激活时半透明化，并在激活时使还原其透明度？
```css
.minimap{opacity:0.5;}
.minimap:hover{opacity:unset;}
/*避免右侧滚动条遮挡*/
.decorationsOverviewRuler{opacity:0.5;}
```
![image](https://user-images.githubusercontent.com/16488261/40837350-cdcb488e-65cc-11e8-9cf5-45aaf8b720f8.png)
